#
# hydro - mimic Fish's hydro prompt
#

add_newline = false

# A minimal left prompt
format = """$directory$git_branch${custom.git_status_dirty}$git_status$git_metrics$cmd_duration$status$character"""

# no right prompt
right_format = ""

# Timeout for commands executed by starship (in milliseconds)
command_timeout=2000

[character]
success_symbol = "[â±](purple)"
error_symbol = "[â±](red)"
vicmd_symbol = "[â°](cyan)"

[directory]
truncate_to_repo = false
format = "[ $path ]($style)"
style = "fg:text bg:#3B76F0"

# right prompt uses left space padding
[git_branch]
format = '[$branch]($style)'
style = 'bold green'

[git_metrics]
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
added_style = 'bold blue'
deleted_style = 'bold red'
only_nonzero_diffs = false 

[git_status]
format = "[($ahead_behind$stashed)]($style) "
style = "cyan"
stashed = "â‰¡"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "â€¢"
style = "white"
format="[$symbol]($style)"
shell = ["zsh", "--no-rcs", "--no-globalrcs"]

[cmd_duration]
format = '[$duration]($style) '

[line_break]
disabled = true

[status]
disabled = false
pipestatus = true
format = '[$symbol $int]($style)'
symbol = 'âŒ'
success_symbol = 'ï¸âœ…'
not_executable_symbol = 'ğŸš«'
not_found_symbol = 'ğŸ”'
sigint_symbol = 'ğŸ§±'
signal_symbol = 'âš¡'
pipestatus_format = '\[$pipestatus\]($style)'
success_style = 'bold green'
failure_style = 'bold red'
